baseURL = "https://example.org"
languageCode = "ru-ru"
title = "Проектная деятельность | Сайт проекта"
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "О проекте"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Участники"
    url = "/team/"
    weight = 30
  [[menu.main]]
    name = "Журнал"
    url = "/posts/"
    weight = 40
  [[menu.main]]
    name = "Ресурсы"
    url = "/resources/"
    weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # Включаем чтение нашего CSS файла из папки static/css/
  customCSS = ["css/custom.css"]
  
  # Настройки отображения постов
  ShowPostNavLinks = true
  disableSpecial1stPost = true 
  
  # Оставляем тему светлой по умолчанию, чтобы работала кнопка переключения!
  defaultTheme = "light" 
[languages]
  [languages.ru]
    languageName = "Russian"
    weight = 1
    [languages.ru.titleCustom]
      posts = "Журнал прогресса"
