baseURL = "https://beatris220.github.io/my-project/"
languageCode = "ru-ru"
title = "Проектная деятельность | Сайт проекта"
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "О проекте"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Участники"
    url = "/team/"
    weight = 30
  [[menu.main]]
    name = "Журнал"
    url = "/posts/"
    weight = 40
  [[menu.main]]
    name = "Ресурсы"
    url = "/resources/"
    weight = 50

[params]
  defaultTheme = "dark"
  disableSpecial1stPost = true
  ShowPostNavLinks = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
