baseURL = "https://beatris220.github.io/my-project/"
languageCode = "ru-ru"
defaultContentLanguage = "ru"
title = "Проектная деятельность | Сайт проекта"
theme = "mainroad"

[languages]
  [languages.ru]
    languageName = "Русский"
    weight = 1

[menu]
  [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "О проекте"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Участники"
    url = "/team/"
    weight = 30
  [[menu.main]]
    name = "Журнал"
    url = "/journal/"
    weight = 40
  [[menu.main]]
    name = "Ресурсы"
    url = "/resources/"
    weight = 50

[params]
  style = "dark"
  color = "blue"
  sidebar = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
